/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rp199

import com.fasterxml.jackson.module.kotlin.kotlinModule
import com.rp199.resource.HelloWorldResource
import com.rp199.configuration.AppConfig
import io.dropwizard.core.Application
import io.dropwizard.core.setup.Bootstrap
import io.dropwizard.core.setup.Environment
import io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper


fun main(args: Array<String>) {
    App().run("server")
}

class App : Application<AppConfig>() {

    override fun initialize(bootstrap: Bootstrap<AppConfig>) {
        bootstrap.objectMapper.registerModule(kotlinModule())
        super.initialize(bootstrap)
    }
    override fun run(config: AppConfig, environment: Environment) {
        val resource = HelloWorldResource()
        environment.jersey().register(resource)
        environment.jersey().register(JsonProcessingExceptionMapper(true))
    }
}
